### ISSUE TITLE
Add support for oam-dev terraform controller

### ISSUE THREAD

**Issue by myjaffoo** [appvia/tf2helm#5]
Users should be able to choose which terraform controller / operator to use. 

- Introduce the oam-dev terraform controller as another option e.g. https://github.com/oam-dev/terraform-controller/tree/master/examples/aws.
- Default to the terraform operator if a `--crd` or `--operator` flag is not specified.

**Comment by gambol99** [comment]
Shall we mark as closed? (https://github.com/appvia/tf2helm/pull/11)

**Comment by myjaffoo** [comment]
relates to #11
